default_connection_name = "SG"

[connections]
[connections.SG]
account = "SG-IDS"
user = "svc_dev_data_streamlit"
database = "dev_raw_sandbox"
schema = "streamlit"
role = "rf_dev_developer_streamlit"

[theme]
primaryColor="#2962ff"
backgroundColor="#131722"
secondaryBackgroundColor="#0c0e15"
textColor="#f6f6f6"