name: Deploy
on:
    push:
      branches:
      - main
env:
    SNOWFLAKE_DEFAULT_CONNECTION_NAME: "workflow"
    SNOWFLAKE_CONNECTIONS_SG_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
    SNOWFLAKE_CONNECTIONS_SG_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
    GITHUB_REF_NAME: main
    GIT_REPO_DB: DEV_RAW_SANDBOX
    GIT_REPO_SCHEMA: STREAMLIT
    GIT_REPO_NAME: SNOW_CLI_STREAMLIT_DEMO
    APP_NAME: demo_config_app
    APP_WH: WH_DEV_DATA_STREAMLIT
    APP_DB: DEV_RAW_SANDBOX
    APP_SCHEMA: STREAMLIT
    DATA_SCHEMA: STREAMLIT
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  # todo update to pick the right branch for deploy
                  ref: ${{ env.GITHUB_REF_NAME  }}
            - uses: Snowflake-Labs/snowflake-cli-action@v1.5
              with:
                  cli-version: "latest"
                  default-config-file-path:
                      ${{ github.workspace }}/config/config.toml
            - name: Check Version and Verify Connection
              env:
                  SNOWFLAKE_CONNECTIONS_SG_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
              run: |
                  snow --version
                  snow connection test --connection="SG"
                  echo "Using branch $GITHUB_REF_NAME"

            - name: Refresh Repo sources
              env:
                  SNOWFLAKE_CONNECTIONS_SG_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
                  GIT_REPO_FQN:
                      ${{ env.GIT_REPO_DB }}.${{ env.GIT_REPO_SCHEMA }}.${{
                      env.GIT_REPO_NAME }}
              run: |
                  echo "Using branch $GIT_REPO_FQN"
                  snow git fetch "$GIT_REPO_FQN" --connection="SG"

            # - name: Setup App Database Objects
            #   env:
            #       SNOWFLAKE_CONNECTIONS_SG_PASSWORD ${{ secrets.SNOWFLAKE_PASSWORD }}
            #       GIT_REPO_FQN:
            #           ${{ env.GIT_REPO_DB }}.${{ env.GIT_REPO_SCHEMA }}.${{
            #           env.GIT_REPO_NAME }}
            #   run: |
            #       snow git execute @"${GIT_REPO_FQN}/branches/${GITHUB_REF_NAME}/de/" \
            #         --variable "db_name='$APP_DB'" \
            #         --variable "schema_name='$DATA_SCHEMA'" \
            #         --variable "wh_name='$APP_WH'" \
            #         --variable "git_repo_name='$GIT_REPO_FQN'" \
            #         --variable "git_branch='$GITHUB_REF_NAME'" \
            #         --database $GIT_REPO_DB --schema $GIT_REPO_SCHEMA
                    
            - name: Deploy config Streamlit Application
              env:
                  SNOWFLAKE_CONNECTIONS_SG_PASSWORD ${{ secrets.SNOWFLAKE_PASSWORD }}
              run: |
                  snow streamlit deploy --replace \
                  --database $APP_DB --schema $APP_SCHEMA --connection="SG"
              working-directory: app

            - name: Get App URL
              env:
                  SNOWFLAKE_CONNECTIONS_SG_PASSWORD ${{ secrets.SNOWFLAKE_PASSWORD }}
              run: |
                  snow streamlit get-url $APP_NAME \
                    --database $APP_DB --schema $APP_SCHEMA --connection="SG"
              working-directory: app
