name: Deploy
on:
    push:
      branches:
      - main
env:
    SNOWFLAKE_DEFAULT_CONNECTION_NAME: "workflow"
    SNOWFLAKE_CONNECTIONS_MYCONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
    SNOWFLAKE_CONNECTIONS_MYCONNECTION_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
    GIT_REPO_DB: MY_GIT_REPOS
    GIT_REPO_SCHEMA: GITHUB
    GIT_REPO_NAME: snow_cli_demo
    TODO_APP_NAME: todos_app
    TODO_APP_WH: TODO_APP_WH
    TODO_APP_DB: TODO_APP_DB
    TODO_APP_SCHEMA: APPS
    TODOS_DATA_SCHEMA: DATA
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  # todo update to pick the right branch
                  ref: ${{ env.GITHUB_REF_NAME  }}
            - uses: Snowflake-Labs/snowflake-cli-action@v1.5
              with:
                  cli-version: "latest"
                  default-config-file-path:
                      ${{ github.workspace }}/config/config.toml
            - name: Check Version and Verify Connection
              env:
                  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
              run: |
                  snow --version
                  snow connection test
                  echo "Using branch $GITHUB_REF_NAME"

            - name: Refresh Repo
              env:
                  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
                  GIT_REPO_FQN:
                      ${{ env.GIT_REPO_DB }}.${{ env.GIT_REPO_SCHEMA }}.${{
                      env.GIT_REPO_NAME }}
              run: |
                  snow git fetch "$GIT_REPO_FQN"

            - name: Setup Todos App Database Objects
              env:
                  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
                  GIT_REPO_FQN:
                      ${{ env.GIT_REPO_DB }}.${{ env.GIT_REPO_SCHEMA }}.${{
                      env.GIT_REPO_NAME }}
              run: |
                  snow git execute @"${GIT_REPO_FQN}/branches/${GITHUB_REF_NAME}/de/" \
                    --variable "db_name='$TODO_APP_DB'" \
                    --variable "schema_name='$TODOS_DATA_SCHEMA'" \
                    --variable "wh_name='$TODO_APP_WH'" \
                    --variable "git_repo_name='$GIT_REPO_FQN'" \
                    --variable "git_branch='$GITHUB_REF_NAME'" \
                    --database $GIT_REPO_DB --schema $GIT_REPO_SCHEMA

            - name: Deploy TODOs Streamlit App
              env:
                  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
              run: |
                  snow streamlit deploy --replace \
                  --database $TODO_APP_DB --schema $TODO_APP_SCHEMA
              working-directory: app

            - name: Get App URL
              env:
                  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
              run: |
                  snow streamlit get-url $TODO_APP_NAME \
                    --database $TODO_APP_DB --schema $TODO_APP_SCHEMA
              working-directory: app
